app/myapp/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(80))

    def __init__(self, username='', email='', password=''):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def is_authenticated(self):
        return True
    def is_active(self):
        return True
    def is_anonymous(self):
        return False
    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User %r>' % self.username

app/myapp/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email

class LoginForm(Form):
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

class RegisterForm(Form):
    username = TextField('Username', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])

app/__init__.py
# Import flask and template operators
from flask import Flask, render_template
from flask.ext.login import LoginManager

# Import SQLAlchemy
from flask.ext.sqlalchemy import SQLAlchemy

# Define the WSGI application object
app = Flask(__name__)

# Configurations
app.config.from_object('config')

# Define the database object which is imported
# by modules and controllers
db = SQLAlchemy(app)

# Define the login manager and initialise it
login_manager = LoginManager()
login_manager.init_app(app)

# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

# Import a module / component using its blueprint handler variable (myapp)
from app.myapp.controllers import myapp

# Register blueprint(s)
app.register_blueprint(myapp, url_prefix='/myapp')

# Build the database:
# This will create the database file using SQLAlchemy
db.create_all()

app/myapp/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import login_user, logout_user, current_user

from app import db
from app import login_manager
from app.myapp.models import User
from app.myapp.forms import LoginForm, RegisterForm

myapp = Blueprint('myapp', __name__)

@login_manager.user_loader
def load_user(userid):
    return User.query.filter_by(id=userid).first()

@myapp.route('/')
def show_users():
    users = User.query.all()
    logged_in = current_user

    return render_template('myapp/show_users.html', title='Users', users=users, logged_in=logged_in)

@myapp.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(username=request.form['username']).first()
            if user and user.check_password(request.form['password']):
                login_user(user)
                return redirect(url_for('myapp.show_users'))
            else:
                error = 'Incorrect username or password'
        else:
            error = 'Form validation error'

    return render_template('myapp/login.html', error=error, form=form)

@myapp.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('myapp.show_users'))

@myapp.route('/register', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User()
            form.populate_obj(user)
            user.password = generate_password_hash(form.password.data)

            db.session.add(user)
            db.session.commit()

            login_user(user)
            return redirect(url_for('myapp.show_users'))
        else:
            error = 'Form validation error'

    return render_template('myapp/register.html', error=error, form=form)

app/templates/myapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      {% block body %}{% endblock %}
    </div>
  </body>
</html

app/templates/myapp/login.html
{% extends "myapp/base.html" %}
{% block body %}
  <h1>Login</h1>
  {% if error %}
    <div class="alert alert-danger">
      <strong>Error:</strong> {{ error }}
    </div>
  {% endif %}
  <form class="form-horizontal" action="{{ url_for('myapp.login') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="col-sm-2 control-label") }}
      <div class="col-sm-10">
        {{ form.username(class="form-control", placeholder="Username") }}
      </div>
    </div>
    <div class="form-group">
      {{ form.password.label(class="col-sm-2 control-label") }}
      <div class="col-sm-10">
        {{ form.password(class="form-control", placeholder="Password") }}
      </div>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
{% endblock %}

app/templates/myapp/register.html
{% extends "myapp/base.html" %}
{% block body %}
  <h1>Register</h1>
  {% if error %}
    <div class="alert alert-danger">
      <strong>Error:</strong> {{ error }}
    </div>
  {% endif %}
  <form class="form-horizontal" action="{{ url_for('myapp.register') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="col-sm-2 control-label") }}
      <div class="col-sm-10">
        {{ form.username(class="form-control", placeholder="Username") }}
      </div>
    </div>
    <div class="form-group">
      {{ form.email.label(class="col-sm-2 control-label") }}
      <div class="col-sm-10">
        {{ form.email(class="form-control", placeholder="Email") }}
      </div>
    </div>
    <div class="form-group">
      {{ form.password.label(class="col-sm-2 control-label") }}
      <div class="col-sm-10">
        {{ form.password(class="form-control", placeholder="Password") }}
      </div>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
{% endblock %}

app/templates/myapp/show_users.html
{% extends "myapp/base.html" %}
{% block body %}
  <h1>Users</h1>
  <ul>
    {% for user in users %}
      {% if user == logged_in %}
        <li><b>{{ user.username }} | {{ user.email }} | {{ user.password }}</b></li>
      {% else %}
        <li>{{ user.username }} | {{ user.email }} | {{ user.password }}</li>
      {% endif %}
    {% endfor %}
  </ul>
  {% if current_user.is_active() %}
    <a href="{{ url_for('myapp.logout') }}">Logout</a>
  {% else %}
    <a href="{{ url_for('myapp.login') }}">Login</a>
    <a href="{{ url_for('myapp.register') }}">Register</a>
  {% endif %}
{% endblock %}